### ISSUE TITLE
[BUG] - No scroll on side-bar

### ISSUE THREAD

**Issue by SKULLXL** [nhcarrigan/BeccaBot-documentation#54]
# Bug Report

## Describe the bug
In the documentation page the side-bar. cant be scrolled down.

The side bar has no option to be scrolled down on. As a result, anything after Manual commands cant be seen.
## Expected behavior
The side-bar was expected to be scrolled down.

## Screenshots
![image](https://user-images.githubusercontent.com/68315325/98636438-0c436a80-2351-11eb-9cf9-d4299f9bd65c.png)

**Comment by nhcarrigan** [comment]
Thanks for catching this~!

It looks like it could be fixed by adding `overflow-y: scroll;` to the `nav` CSS selector. Then, to hide the scrollbar, we need:
```css
nav::-webkit-scrollbar {
  width: 0px;
}
```

**Comment by nhcarrigan** [comment]
@all-contributors please add @SKULLXL for bugs

**Comment by nhcarrigan** [comment]
Also may need to add these properties to the `nav` for cross-browser compatibility:
```css
-ms-overflow-style: none;  /* Internet Explorer 10+ */
    scrollbar-width: none;  /* Firefox */
```
