### ISSUE TITLE
[FEAT] - Style a Custom Scrollbar

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/BeccaBot-documentation#55]
# Feature Request

## Is your feature request related to a problem? Please describe:

The page currently uses the default browser scrollbar.

## Describe the solution you'd like

Let's write some custom styling (either through CSS or JS) to have our own scrollbar.

**Comment by SKULLXL** [comment]
What kinda custom scroll-bar is wanted here. for example wll a purple thumb like scroll-bar work like the image
![image](https://user-images.githubusercontent.com/68315325/98644423-a52ab380-235a-11eb-9ce0-9a53b6b5c126.png)
